version: '3'
services:
#rabbitmq
 rabbitmq:
  image: rabbitmq:3-management
  environment:
   - RABBITMQ_USERNAME=root
   - RABBITMQ_PASSWORD=test123
  ports:
   - '15672:15672'
  networks:
   - app-network
 #PHP Service
 picpay-php-fpm:
  build:
   dockerfile: Dockerfile
  image: php:8.2-fpm
  container_name: picpay-php-fpm
  restart: unless-stopped
  tty: true
  environment:
   SERVICE_NAME: picpay-php-fpm
   SERVICE_TAGS: dev
  working_dir: /var/www/
  volumes:
   - ./Account/:/var/www/Account/
   - ./Transaction/:/var/www/Transaction/
   - ./app.conf:/etc/nginx/conf.d/app.conf
  networks:
   - app-network

 #Nginx Service
 picpay-nginx:
  image: nginx:alpine
  container_name: picpay-nginx
  restart: unless-stopped
  tty: true
  ports:
   - "80:80"
   - "81:81"
   - "82:82"
  volumes:
   - ./Account/:/var/www/Account/
   - ./Transaction/:/var/www/Transaction/
   - ./app.conf:/etc/nginx/conf.d/app.conf
  networks:
   - app-network
  depends_on:
   - picpay-php-fpm

 #MySQL Service
 picpay-mysql:
  image: mysql:latest
  container_name: picpay-mysql
  restart: unless-stopped
  tty: true
  ports:
   - "3306:3306"
  environment:
   MYSQL_DATABASE: picpay
   MYSQL_ROOT_PASSWORD: test123
   SERVICE_TAGS: dev
   SERVICE_NAME: mysql
  volumes:
   - mysql_data:/var/lib/mysql/
  networks:
   - app-network

#Docker Networks
networks:
 app-network:
  driver: bridge
#Volumes
volumes:
 mysql_data:
  driver: local